services:
  - type: web
    name: shell-eco-marathon-back
    env: node
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
